# Generated by Django 5.0.2 on 2024-02-17 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('RC', 'Recepcionista'), ('TC', 'Técnico'), ('GE', 'Gerente')], default='EN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('endereco', models.TextField()),
                ('cidade', models.CharField(max_length=12)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('preco', models.IntegerField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.IntegerField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('RE', 'Recepção'), ('OF', 'Oficina'), ('ES', 'Estoque')], default='EN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('nun_serie', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo_funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.cargo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.funcionario')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.equipamento')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.pessoa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.pessoa'),
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('produtos', models.ManyToManyField(to='workflow.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('Cargo_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.cargo_funcionario')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.equipamento')),
                ('produto', models.ManyToManyField(to='workflow.produto')),
                ('servico', models.ManyToManyField(to='workflow.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('EN', 'Entrada'), ('OR', 'Orçamento'), ('MA', 'manutenção'), ('GA', 'entrega'), ('SA', 'Saida')], default='EN', max_length=2)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.historico')),
            ],
        ),
        migrations.AddField(
            model_name='setor',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.status'),
        ),
    ]
