# Generated by Django 5.0.2 on 2024-03-06 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='status',
            name='historico',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='historico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.historico'),
        ),
        migrations.AddField(
            model_name='historico',
            name='status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.status'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(max_length=50),
        ),
    ]
