# Generated by Django 5.0.2 on 2024-03-06 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_equipamento_historico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='historico',
            new_name='historico_id',
        ),
    ]
