# Generated by Django 5.0.2 on 2024-03-06 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_rename_historico_equipamento_historico_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='historico_id',
        ),
    ]
