# Generated by Django 5.0.2 on 2024-03-06 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_remove_equipamento_historico_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico',
        ),
    ]
