# Generated by Django 5.0.2 on 2024-03-06 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_delete_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workflow.status')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='historico_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workflow.historico'),
        ),
    ]
