# Generated by Django 5.0.2 on 2024-03-06 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_historico_equipamento_historico_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.status'),
        ),
    ]
