# Generated by Django 5.0.2 on 2024-03-06 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_alter_status_historico_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='date_saida',
        ),
        migrations.RemoveField(
            model_name='status',
            name='historico_id',
        ),
        migrations.AddField(
            model_name='historico',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
