# Generated by Django 5.0.2 on 2024-03-06 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_remove_status_date_saida_remove_status_historico_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='date_saida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
