# Generated by Django 5.0.2 on 2024-03-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_remove_pessoa_endereco_pessoa_bairro_pessoa_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
