# Generated by Django 5.0.2 on 2024-10-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_alter_cliente_cidade_alter_funcionario_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
