# Generated by Django 5.0.2 on 2024-10-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_alter_status_date_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='historico_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.historico'),
        ),
    ]
