# Generated by Django 5.0.2 on 2025-06-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_alter_equipamento_historico_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='status',
        ),
    ]
