# Generated by Django 5.0.2 on 2025-06-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_remove_setor_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='Cargo_funcionario',
            new_name='cargo_funcionario',
        ),
    ]
