# Generated by Django 5.0.2 on 2025-08-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_rename_cargo_funcionario_orcamento_cargo_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='historico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', related_query_name='status', to='workflow.historico'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historicos_vigentes', related_query_name='historico_vigente', to='workflow.status'),
        ),
    ]
