# Generated by Django 5.0.2 on 2025-08-26 21:39

import workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_equipamento_qr_slug_funcionario_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='qr_slug',
            field=models.SlugField(default=workflow.models.generate_qr_slug, max_length=32, unique=True),
        ),
    ]
