# Generated by Django 5.0.2 on 2025-09-13 16:11

import workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_alter_equipamento_qr_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='qr_slug',
            field=models.SlugField(default=workflow.models.generate_qr_slug, max_length=64, unique=True),
        ),
    ]
